export default [
  {
    product_id: '1',
    product_name: 'Banana',
    product_category: 'fruit',
    product_image: require('../../assets/images/banana.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
  {
    product_id: '2',
    product_name: 'Onion',
    product_category: 'fruit',
    product_image: require('../../assets/images/Onion.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
  {
    product_id: '2',
    product_name: 'apple',
    product_category: 'fruit',
    product_image: require('../../assets/images/apple.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
  {
    product_id: '2',
    product_name: 'Onion',
    product_category: 'fruit',
    product_image: require('../../assets/images/Onion.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
  {
    product_id: '2',
    product_name: 'apple',
    product_category: 'fruit',
    product_image: require('../../assets/images/apple.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
  {
    product_id: '5',
    product_name: 'apple',
    product_category: 'fruit',
    product_image: require('../../assets/images/apple.jpg'),
    product_price: '300',
    product_quanity: '5',
    dozen: false,
    kg: true,
  },
];
